name: Upload to cPanel via FTP
  uses: SamKirkland/FTP-Deploy-Action@v4
  with:
    server: ${{ secrets.FTP_SERVER }}
    username: ${{ secrets.FTP_USERNAME }}
    password: ${{ secrets.FTP_PASSWORD }}
    port: ${{ secrets.FTP_PORT || 21 }}
    protocol: ftp        # <— MUDAR de ftps para ftp
    local-dir: ./
    server-dir: public_html/
    exclude: |
      **/.git**
      **/.github/**
      node_modules/**
      vendor/**
      storage/**
      wp-content/uploads/**
      **/.env
      **/*.env
