name: Deploy via FTP (cPanel)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - name: Upload to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT || 21 }}
          protocol: ftp           # usa ftp; muda para ftps quando possível
          passive: true
          local-dir: ./
          server-dir: /public_html/
          exclude: |
            **/.git**
            **/.github/**
            **/config.local.php
            **/config.prod.php
            node_modules/**
            vendor/**
            storage/**
            wp-content/uploads/**
            **/.env
            **/*.env
          log-level: verbose
